apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/sela-tracks/1099/students/amirp/finalproject/finalproject/argodeploygitops'
    targetRevision: HEAD
    path: ./data-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
