version: "3.8"
services: 
  db: 
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gozo9XcrVI
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app: 
    build: .
    ports: 
      - "5000:5000" 
    depends_on:
      - db 

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db

volumes: 
  postgres_data: 